modLoader="javafml"
loaderVersion="[36,)"
license="WTFPL"
[[mods]]
modId="hitindication"
version="1.1.1"
displayName="Hit Indication"
logoFile="Hit_Indication.png"
credits=""
authors="Hamester and Axovoxel"
description="Adds configurable hit indicators."
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
